version: '3'

networks:
  backend:
    driver: bridge

volumes:                              
  dir-db:                          
    driver_opts:
      device: ./db               
      o: bind
      type: none

services:
  mysql:
    image:  "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=sonduong
      - MYSQL_PASSWORD=sonduong
      - MYSQL_DATABASE=training
    volumes:
      - dir-db:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    hostname: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports: 
      - "8080:80"
    networks:
      - backend

